// Command anssimatrix generates catalogue/ANSSI-COVERAGE.md: every ANSSI /
// CERT-FR Active Directory control point, which catalogue entries implement
// it, and when the remaining ones are scheduled. It also enforces that the
// plan accounts for every point, so the matrix cannot silently drop one.
//
//	go run ./tools/anssimatrix            # write the file
//	go run ./tools/anssimatrix -check     # fail if the committed file is stale
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/atsvetko/directory-auditor/internal/catalogue"
)

type planItem struct {
	ID     string `yaml:"id"`
	Status string `yaml:"status"` // partial | gap | collect
	Wave   int    `yaml:"wave"`
	Note   string `yaml:"note"`
	Needs  string `yaml:"needs"`
}

func main() {
	dir := flag.String("catalogue", "catalogue", "catalogue directory")
	check := flag.Bool("check", false, "verify the committed matrix is up to date instead of writing it")
	flag.Parse()

	fw, err := catalogue.LoadANSSIDir(*dir)
	must(err)
	entries, err := catalogue.LoadDir(*dir)
	must(err)
	cov := catalogue.Coverage(entries)

	raw, err := os.ReadFile(*dir + "/frameworks/anssi-plan.yaml")
	must(err)
	var pf struct {
		Plan []planItem `yaml:"plan"`
	}
	dec := yaml.NewDecoder(bytes.NewReader(raw))
	dec.KnownFields(true)
	must(dec.Decode(&pf))
	plan := map[string]planItem{}
	for _, p := range pf.Plan {
		if _, dup := plan[p.ID]; dup {
			fail("plan lists %s twice", p.ID)
		}
		plan[p.ID] = p
	}

	// Completeness and consistency.
	idx := fw.Index()
	for id := range plan {
		if _, ok := idx[id]; !ok {
			fail("plan entry %s is not an ANSSI point", id)
		}
	}
	for _, p := range fw.Points {
		pi, inPlan := plan[p.ID]
		tagged := len(cov[p.ID]) > 0
		switch {
		case !tagged && !inPlan:
			fail("ANSSI point %s is neither implemented nor planned", p.ID)
		case inPlan && pi.Status == "partial" && !tagged:
			fail("%s is marked partial but no entry declares it", p.ID)
		case inPlan && pi.Status != "partial" && tagged:
			fail("%s is planned as %s but %v already declare it — mark it partial or drop it from the plan", p.ID, pi.Status, cov[p.ID])
		case inPlan && pi.Status != "partial" && pi.Status != "gap" && pi.Status != "collect":
			fail("%s has unknown status %q", p.ID, pi.Status)
		}
	}

	out := render(fw, cov, plan)
	path := *dir + "/ANSSI-COVERAGE.md"
	if *check {
		cur, _ := os.ReadFile(path)
		if !bytes.Equal(cur, out) {
			fail("%s is out of date: run go run ./tools/anssimatrix", path)
		}
		fmt.Println("ANSSI-COVERAGE.md is up to date")
		return
	}
	must(os.WriteFile(path, out, 0o644))
	fmt.Printf("wrote %s\n", path)
}

func status(id string, cov map[string][]string, plan map[string]planItem) (string, planItem) {
	pi, inPlan := plan[id]
	switch {
	case inPlan && pi.Status == "partial":
		return "partial", pi
	case len(cov[id]) > 0:
		return "covered", pi
	case inPlan && pi.Status == "collect":
		return "collect", pi
	default:
		return "gap", pi
	}
}

func render(fw catalogue.ANSSIFramework, cov map[string][]string, plan map[string]planItem) []byte {
	points := append([]catalogue.ANSSIPoint(nil), fw.Points...)
	sort.SliceStable(points, func(i, j int) bool {
		if points[i].MinLevel() != points[j].MinLevel() {
			return points[i].MinLevel() < points[j].MinLevel()
		}
		return points[i].ID < points[j].ID
	})

	type tally struct{ total, covered, partial int }
	byLevel := map[int]*tally{}
	waves := map[int]int{}
	var all tally
	for _, p := range points {
		st, pi := status(p.ID, cov, plan)
		l := p.MinLevel()
		if byLevel[l] == nil {
			byLevel[l] = &tally{}
		}
		byLevel[l].total++
		all.total++
		switch st {
		case "covered":
			byLevel[l].covered++
			all.covered++
		case "partial":
			byLevel[l].partial++
			all.partial++
		}
		if st != "covered" {
			waves[pi.Wave]++
		}
	}

	var b bytes.Buffer
	w := func(f string, a ...any) { fmt.Fprintf(&b, f, a...) }
	w("# ANSSI coverage\n\n")
	w("<!-- Generated by `go run ./tools/anssimatrix` from frameworks/anssi.yaml, frameworks/anssi-plan.yaml\n")
	w("     and the `anssi:` field of each entry. Do not edit by hand; CI fails if it is stale. -->\n\n")
	w("Directory Auditor's checks mapped to the ANSSI / CERT-FR *Points de contrôle Active Directory*\n")
	w("(%s, version %s — %d control points). Checks are written in our own words from primary\n", fw.Source, fw.Version, len(fw.Points))
	w("sources; this page only maps identifiers. A point is **covered** when an entry declares it in its\n")
	w("`anssi:` field, **partial** when that entry covers part of it, and otherwise scheduled in a wave.\n\n")
	pct := func(n, d int) string {
		if d == 0 {
			return "—"
		}
		return fmt.Sprintf("%d%%", (n*100+d/2)/d)
	}
	w("## Summary\n\n")
	w("| ANSSI level | Points | Covered | Partial | Covered + partial |\n|---|---:|---:|---:|---:|\n")
	levels := make([]int, 0, len(byLevel))
	for l := range byLevel {
		levels = append(levels, l)
	}
	sort.Ints(levels)
	for _, l := range levels {
		t := byLevel[l]
		w("| %d | %d | %d | %d | %s |\n", l, t.total, t.covered, t.partial, pct(t.covered+t.partial, t.total))
	}
	w("| **All** | **%d** | **%d** | **%d** | **%s** |\n\n", all.total, all.covered, all.partial, pct(all.covered+all.partial, all.total))

	w("Remaining points by wave: ")
	wk := make([]int, 0, len(waves))
	for k := range waves {
		wk = append(wk, k)
	}
	sort.Ints(wk)
	parts := make([]string, 0, len(wk))
	names := map[int]string{1: "level-1/2 on current collection", 2: "level-1/2 needing a targeted read", 3: "level-3/4", 4: "AD CS", 5: "DNS"}
	for _, k := range wk {
		parts = append(parts, fmt.Sprintf("wave %d (%s) %d", k, names[k], waves[k]))
	}
	w("%s.\n\n", strings.Join(parts, " · "))

	w("## Control points\n\n")
	w("| Level | ANSSI point | Title | Status | Directory Auditor |\n|---|---|---|---|---|\n")
	for _, p := range points {
		st, pi := status(p.ID, cov, plan)
		lv := strings.Trim(strings.Join(strings.Fields(fmt.Sprint(p.Levels)), ","), "[]")
		var cell string
		switch st {
		case "covered":
			cell = strings.Join(cov[p.ID], ", ")
		case "partial":
			cell = strings.Join(cov[p.ID], ", ") + fmt.Sprintf(" — wave %d: %s", pi.Wave, pi.Note)
		case "collect":
			cell = fmt.Sprintf("wave %d — needs %s", pi.Wave, pi.Needs)
		default:
			cell = fmt.Sprintf("wave %d — %s", pi.Wave, pi.Note)
		}
		label := map[string]string{"covered": "✅ covered", "partial": "🟡 partial", "gap": "⬜ planned", "collect": "⬜ planned"}[st]
		w("| %s | `%s` | %s | %s | %s |\n", lv, p.ID, p.TitleEN, label, cell)
	}
	return b.Bytes()
}

func must(err error) {
	if err != nil {
		fail("%v", err)
	}
}

func fail(f string, a ...any) {
	fmt.Fprintf(os.Stderr, "anssimatrix: "+f+"\n", a...)
	os.Exit(1)
}
